openapi: 3.0.2
info:
  title: erxBank
  version: 1.0.0
paths:
  /users:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/postUsersRequest'
        required: true
      tags:
        - users
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/userObject'
          description: User successfully registered
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
              examples:
                Invalid password:
                  value:
                    error: Invalid password
                Parameter is required:
                  value:
                    error: 'User validation failed: (param): Path (param) is required.'
          description: Bad request
        '409':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
              examples:
                Username already exists:
                  value:
                    error: Username already exists
          description: Username already exist
      summary: Registers a new user
components:
  schemas:
    userObject:
      title: userObject
      description: ''
      type: object
      properties:
        accounts:
          description: Array of user's bank accounts
          type: array
          items:
            $ref: '#/components/schemas/accountObject'
        password:
          type: string
        name:
          description: User's full name
          type: string
        username:
          type: string
        id:
          description: User's ID
          type: string
      example:
        id: 5f7ed36f7901dd2c65c57a8e
        name: Sasuke Uchiha
        username: sasuke
        accounts:
          -
            name: Main
            balance: 100000
            currency: EUR
            number: erx6877e78200596839a6b30c655efaaf29
            id: 5f7ed36f7901dd2c65c57a8f
    postUsersRequest:
      title: POST /users request
      description: ''
      required:
        - name
        - username
        - password
      type: object
      properties:
        name:
          description: User's full name
          type: string
        username:
          description: Desired username
          type: string
        password:
          format: password
          description: Desired password
          type: string
      example:
        name: Sasuke Uchiha
        username: sasuke
        password: narutouzumaki
    accountObject:
      title: accountObject
      description: ''
      type: object
      properties:
        name:
          description: Account's name
          type: string
        balance:
          format: int32
          description: The funds the account holds
          type: integer
        currency:
          description: The currency of the funds
          type: string
        number:
          description: Account's number
          type: string
      example:
        name: Main
        balance: 100000
        currency: EUR
        number: erx896925e436c5f72a807f31e57439eb2d
    errorResponse:
      title: Root Type for errorObject
      description: ''
      type: object
      properties:
        error:
          type: string
      example:
        error: error message.
